apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: Opaque
stringData:
  POSTGRES_HOST: "10.12.1.5"
  POSTGRES_PASSWORD: "life1234"
  POSTGRES_USER: "admin"
  RAILS_MASTER_KEY: "c1e0008dd2a1e7a2a3875ff911e3a076"